name: 'Prefect Cloud agent on Compute Engine'
branding:
  icon: cloud
  color: blue
description: 'Test action'
inputs:
  prefect_api_key:
    description: 'Prefect Cloud API key'
    required: true
  prefect_api_url:
    description: 'Prefect Cloud API URL'
    required: true
  gcp_project_id:
    description: 'Name of the GCP Project ID'
    required: true
  gcp_sa_email:
    description: 'Email of the Service Account'
    required: true
  gcp_credentials_json:
    description: 'Content of the Service Account JSON key file'
    required: true
  region:
    description: 'GCP region'
    required: false
    default: 'us-east1'
  zone:
    description: 'Zone in the selected GCP region'
    required: false
    default: 'b'
  machine_type:
    description: 'GCP Compute Engine instance type'
    required: false
    default: 'e2-micro'
  machine_name:
    description: 'GCP Compute Engine instance name'
    required: false
    default: 'prefect-vm'
  artifact_repository:
    description: 'Artifact Registry Repository Name'
    required: false
    default: prefect

runs:
  using: "composite"
  steps:
    - name: Login to GAR
      uses: docker/login-action@v2
      with:
        registry: '${{ inputs.region }}-docker.pkg.dev'
        username: _json_key
        password: ${{ inputs.gcp_credentials_json }}
    - id: image
      run: echo "IMAGE_URI=${{ inputs.region }}-docker.pkg.dev/${{ inputs.gcp_project_id }}/${{ inputs.artifact_repository }}/agent:latest" >> $GITHUB_ENV
      shell: bash
    - id: build-image
      run: |
        docker build --build-arg PREFECT_API_KEY=${{ inputs.prefect_api_key }} --build-arg PREFECT_API_URL=${{ inputs.prefect_api_url }} -t "${{ env.IMAGE_URI }}" -f Dockerfile.agent .
        docker push "${{ env.IMAGE_URI }}"
      shell: bash

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: "${{ inputs.gcp_credentials_json }}"

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - id: delete
      run: gcloud compute instances delete "${{ inputs.machine_name }}" --zone "${{ inputs.zone }}" --quiet
      continue-on-error: true
      shell: bash

    - id: deploy
      shell: bash
      run: |
        gcloud compute instances create-with-container "${{ inputs.machine_name }}" \
          --zone "${{ inputs.zone }}" \
          --machine-type "${{ inputs.machine_type }}" \
          --service-account "${{ inputs.gcp_sa_email }}" \
          --scopes "cloud-platform" \
          --container-image "${{ env.IMAGE_URI }}"
